input:
  type: csv
  properties:
    path: queries/source/miaou.csv
    target_column: content
    separator: "\t"

pipeline:
  - type: generation
    method: async-llm
    parameters:
      provider: mistral
      model: mistral-large-latest
      temperature: 0.7
      instruction_mode: "all_combinations"
      batch_size: 40
      template: |
        Convert this sentence to a 'you' sentence:
        {source}
        Answer directly the converted sentence, without any other text.

  - type: clean
    method: deduplicate-embed
    parameters:
      provider: mistral
      model: mistral-embed
      similarity_threshold: 0.7

output:
  type: csv
  properties:
    path: queries/output/test.csv
    separator: ","
    columns: ["value", "metadata"]  # metadata contiendra les instructions utilisées